"""
AutoDevAgent - Mock Mode Implementation
Runs without requiring external API keys for demonstration and hackathon deployment.
"""

import os

class AutoDevAgent:
    def __init__(self):
        # Allow running without API key using mock mode
        self.api_key = os.environ.get("NEBIUS_API_KEY") or "mock_key_for_demo"

    def generate(self, requirement: str, target_stack: str, mode: str) -> dict:
        """
        Generates simulated professional code and documentation based on user requirements.
        """
        # Tailor output based on selected stack
        if "Flask" in target_stack:
            code = """from flask import Flask, jsonify, request

app = Flask(__name__)

@app.route('/api/v1/health', methods=['GET'])
def health_check():
    return jsonify({"status": "healthy", "agent": "Nemotron Auto-Dev"})

@app.route('/api/v1/data', methods=['POST'])
def process_data():
    req_data = request.get_json()
    # Process user requirement logic securely
    return jsonify({
        "message": "Successfully processed by Nemotron Agent",
        "input": req_data
    }), 200

if __name__ == '__main__':
    app.run(debug=True, port=5000)
"""
        elif "FastAPI" in target_stack:
            code = """from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="Nemotron Auto-Dev API")

class Item(BaseModel):
    name: str
    description: str = None

@app.get("/")
def read_root():
    return {"message": "Hello from Nemotron Auto-Dev Agent"}

@app.post("/items/")
def create_item(item: Item):
    return {"status": "success", "created_item": item}
"""
        else:
            code = f"""# Generated by Nemotron Auto-Dev Agent
# Requirement: {requirement}
# Target Stack: {target_stack}

def main():
    print("Initializing automated workflow...")
    print("Executing task successfully based on specifications.")

if __name__ == "__main__":
    main()
"""

        docs = f"""### 📋 Architecture & Implementation Guide

**Target Tech Stack:** {target_stack}  
**Generation Mode:** {mode}  

#### 1. Overview
This module was automatically generated to address the following requirement:
> *{requirement}*

#### 2. Key Components
- **Core Logic:** Handles robust execution and error boundaries.
- **API Endpoints:** Structured with clean separation of concerns.
- **Security & Validation:** Implemented input sanitization and verification layers.

#### 3. Deployment Instructions
1. Install dependencies: `pip install -r requirements.txt`
2. Run the application script.
"""

        return {
            "code": code,
            "docs": docs
        }
